version: "3"
services:

  zhihu:
    image: novio/zhihu:0.1
    build: docker/zhihu
    ports:
      - 8080:8080
    networks:
      - backend
    links:
      - mysql
      - redis
    volumes:
      - ~/go:/go
      - ./:/go/src/github.com/novioleo/zhihu
    depends_on:
      - mysql
      - redis
    restart: on-failure
  adminer:
    image: dehy/adminer:4.7.1
    restart: always
    ports:
      - 8989:80
    networks:
      - backend
    links:
      - mysql
  mysql:
    image: mysql:5.7
    networks:
      - backend
    volumes:
      - /var/lib/mysql
      - ./docker/mysql_init:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
  redis:
    image: redis:4-alpine
    networks:
      - backend

networks:
  backend: